Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
  VPCInternetGateway:
    Type: 'AWS::EC2::InternetGateway'
  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref VPCInternetGateway
  CanaryECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties: {}
  CanaryTaskExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: CanaryTaskExecutionRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: AmazonECSTaskExecutionPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 'logs:DescribeLogStreams'
                  - 'logs:GetLogEvents'
                  - 'cloudwatch:PutMetricData'
                Resource: '*'
  CanaryTaskEventRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: CanaryTaskEventRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: AmazonEC2ContainerServiceEventsRole
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'ecs:RunTask'
                  - 'iam:PassRole'
                Resource: '*'
Outputs:
  VPCId:
    Description: "Canary VPC ID"
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}-VpcId"
  VPCInternetGatewayId:
    Description: "Canary VPC Internet Gateway ID"
    Value: !Ref VPCInternetGateway
    Export:
      Name: !Sub "${AWS::StackName}-VpcInternetGatewayId"
  ECSClusterArn:
    Description: "ECS Cluster ARN"
    Value: !GetAtt CanaryECSCluster.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ECSClusterArn"
  CanaryTaskExecutionRoleArn:
    Description: "Canary Task Execution Role ARN"
    Value: !GetAtt CanaryTaskExecutionRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-CanaryTaskExecutionRoleArn"
  CanaryTaskEventRoleArn:
    Description: "Canary Task Event Role ARN"
    Value: !GetAtt CanaryTaskEventRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-CanaryTaskEventRoleArn"
