Parameters:
  CanaryInfraStack:
    Type: String
  TaskName:
    Type: String
    Default: repo-validation-canary
  SNSSubscriptionEndpoint:
    Type: String
  SNSSubscriptionProtocol:
    Type: String
    Default: email
  RepoMetadataBaseUrl:
    Type: String
  RepoTargetBaseUrl:
    Type: String
Resources:
  VPCRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId:
        Fn::ImportValue:
          !Sub "${CanaryInfraStack}-VpcId"
  ExternalRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Fn::ImportValue:
          !Sub "${CanaryInfraStack}-VpcInternetGatewayId"
      RouteTableId: !Ref VPCRouteTable
  VPCSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 10.0.0.0/24
      VpcId:
        Fn::ImportValue:
          !Sub "${CanaryInfraStack}-VpcId"
  SubnetRouteAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref VPCRouteTable
      SubnetId: !Ref VPCSubnet
  VPCSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Sub 'Allow traffic to ${TaskName}'
      VpcId:
        Fn::ImportValue:
          !Sub "${CanaryInfraStack}-VpcId"
  LogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/ecs/${TaskName}'
      RetentionInDays: 30
  FailedStartLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/aws/events/${TaskName}-start-failures'
  RepoValidationFailureLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/aws/events/${TaskName}-failures'
  TUFRepoCanarySNSNotificationTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: TUF Repo Canary Notifications
  TUFRepoCanarySNSSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Endpoint: !Sub '${SNSSubscriptionEndpoint}'
      Protocol: !Sub '${SNSSubscriptionProtocol}'
      TopicArn: !Ref TUFRepoCanarySNSNotificationTopic
  TUFRepoCanaryImgRepo:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: !Sub '${TaskName}'
  TUFRepoCanaryTask:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      TaskRoleArn:
        Fn::ImportValue:
          !Sub "${CanaryInfraStack}-CanaryTaskExecutionRoleArn"
      ExecutionRoleArn:
        Fn::ImportValue:
          !Sub "${CanaryInfraStack}-CanaryTaskExecutionRoleArn"
      Family: !Sub '${TaskName}'
      NetworkMode: awsvpc
      Cpu: '256'
      Memory: '512'
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Command:
            - '--metadata-base-url'
            - !Sub '${RepoMetadataBaseUrl}'
            - '--target-base-url'
            - !Sub '${RepoTargetBaseUrl}'
            - '--trusted-root-path'
            - '/usr/share/repo-validation-canary/root.json'
            - '--percentage-of-targets-to-retrieve'
            - '30'
          Memory: 512
          Cpu: 256
          Image: !Join
            - /
            - - !Join
                - .
                - - !Ref 'AWS::AccountId'
                  - dkr.ecr
                  - !Ref 'AWS::Region'
                  - amazonaws.com
              - !Sub '${TaskName}:latest'
          Name: !Sub '${TaskName}'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: 'ecs'
  TUFRepoCanaryFailedInvocationAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: TUF Repo Canary Invocation Failure
      AlarmDescription: 'TUF Repo Canary task could not be invoked'
      Namespace: AWS/Events
      MetricName: FailedInvocations
      Dimensions:
        - Name: RuleName
          Value: !Ref TUFRepoCanaryScheduledTask
      Period: 600
      Statistic: Average
      Threshold: 0
      TreatMissingData: notBreaching
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 4
      DatapointsToAlarm: 3
      ActionsEnabled: true
      AlarmActions:
        - !Ref TUFRepoCanarySNSNotificationTopic
  TUFRepoCanaryScheduledTask:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: !Sub 'Schedules ${TaskName} task to run every 10 minutes'
      ScheduleExpression: cron(0/10 * * * ? *)
      State: ENABLED
      Targets:
        - Id: !Sub '${TaskName}-Fargate-Task'
          RoleArn:
            Fn::ImportValue:
              !Sub "${CanaryInfraStack}-CanaryTaskEventRoleArn"
          EcsParameters:
            TaskDefinitionArn: !Ref TUFRepoCanaryTask
            TaskCount: 1
            LaunchType: FARGATE
            PlatformVersion: LATEST
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: ENABLED
                SecurityGroups:
                  - !Ref VPCSecurityGroup
                Subnets:
                  - !Ref VPCSubnet
          Arn:
            Fn::ImportValue:
              !Sub "${CanaryInfraStack}-ECSClusterArn"
  TUFRepoCanaryFailedAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: TUF Repo Validation Failure
      AlarmDescription: 'TUF Repo Canary task exited non-zero (indicating TUF Repo validation failure)'
      Namespace: AWS/Events
      MetricName: TriggeredRules
      Dimensions:
        - Name: RuleName
          Value: !Ref TUFRepoCanaryFailedRule
      Period: 600
      Statistic: Average
      Threshold: 0
      TreatMissingData: notBreaching
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 4
      DatapointsToAlarm: 3
      ActionsEnabled: true
      AlarmActions:
        - !Ref TUFRepoCanarySNSNotificationTopic
  TUFRepoCanaryFailedRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: 'TUF repository validation failure'
      Name: 'repo-canary-nonzero-exit-code'
      EventPattern: !Sub '{"source": ["aws.ecs"],"detail-type": ["ECS Task State Change"],"detail": {"containers": {"name": ["${TaskName}"],"exitCode":[1,64,65,66,67,68,69,70,71,72,73],"lastStatus": ["STOPPED"]}}}'
      Targets:
        - Arn: !Join
            - ":"
            - - "arn:aws:logs"
              - !Ref 'AWS::Region'
              - !Ref 'AWS::AccountId'
              - 'log-group'
              - !Ref RepoValidationFailureLogGroup
          Id: 'tuf-repo-validation-failure'
  TUFRepoCanaryFailedStartAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: TUF Repo Canary Task Start Failure
      AlarmDescription: 'TUF Repo Canary task failed to start'
      Namespace: AWS/Events
      MetricName: TriggeredRules
      Dimensions:
        - Name: RuleName
          Value: !Ref TUFRepoCanaryFailedStartRule
      Period: 600
      Statistic: Average
      Threshold: 0
      TreatMissingData: notBreaching
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 4
      DatapointsToAlarm: 3
      ActionsEnabled: true
      AlarmActions:
        - !Ref TUFRepoCanarySNSNotificationTopic
  TUFRepoCanaryFailedStartRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: 'TUF Repo Canary fail to start'
      Name: 'repo-canary-failed-to-start'
      EventPattern: !Sub '{"source": ["aws.ecs"],"detail-type": ["ECS Task State Change"],"detail": {"containers": {"name": ["${TaskName}"],"lastStatus": ["STOPPED"]},"stoppedReason":["Task failed to start"]}}'
      Targets:
        - Arn: !Join
            - ":"
            - - "arn:aws:logs"
              - !Ref 'AWS::Region'
              - !Ref 'AWS::AccountId'
              - 'log-group'
              - !Ref FailedStartLogGroup
          Id: !Sub '${TaskName}-failed-start'
