AWSTemplateFormatVersion: "2010-09-09"
Description: Dogswatch container pipeline
Parameters:
  CodeBuildResourceStack:
    Type: String
    Description: 'Enter the name of the CloudFormation stack that sets up the pipeline CodeBuild projects.'
  BranchName:
    Description: GitHub branch name
    Type: String
    Default: develop
    AllowedPattern: "[A-Za-z0-9-]+"
  RepositoryName:
    Description: Repository name
    Type: String
    AllowedPattern: "[A-Za-z0-9-]+"
  GitHubOwner:
    Description: Owner of the repository
    Type: String
    Default: amazonlinux
    AllowedPattern: "[A-Za-z0-9-]+"
  GitHubSecretToken:
    Description: Github personal access token. (Account must have permission to create webhooks)
    Type: String
    NoEcho: true
    MinLength: 40
    MaxLength: 40
    AllowedPattern: '[a-z0-9]*'

Resources:
  CodePipelineServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: !Sub "/${AWS::StackName}/"
      Policies:
        - PolicyName: HostContainerPipelineRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'codebuild:BatchGetBuilds'
                  - 'codebuild:StartBuild'
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                Resource:
                  Fn::Join:
                    - '/'
                    - - Fn::ImportValue: !Sub "${CodeBuildResourceStack}-ArtifactBucketArn"
                      - '*'

  DogswatchCtrPipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: dogswatch-ctr-pipeline
      RoleArn: !GetAtt
        - CodePipelineServiceRole
        - Arn
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: '1'
                Provider: GitHub
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref RepositoryName
                Branch: !Ref BranchName
                OAuthToken: !Ref GitHubSecretToken
                PollForSourceChanges: false
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildAction
              InputArtifacts:
                - Name: SourceOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName:
                  Fn::ImportValue:
                    !Sub "${CodeBuildResourceStack}-Build"
              RunOrder: 1
        - Name: Test
          Actions:
            - Name: TestAction
              InputArtifacts:
                - Name: SourceOutput
                - Name: BuildArtifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName:
                  Fn::ImportValue:
                    !Sub "${CodeBuildResourceStack}-Test"
                PrimarySource: SourceOutput
              RunOrder: 1
        - Name: BetaDeploy
          Actions:
            - Name: BetaDeployAction
              InputArtifacts:
                - Name: SourceOutput
                - Name: BuildArtifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName:
                  Fn::ImportValue:
                    !Sub "${CodeBuildResourceStack}-BetaDeploy"
                PrimarySource: SourceOutput
              RunOrder: 1
      ArtifactStore:
        Type: S3
        Location:
          Fn::ImportValue:
            !Sub "${CodeBuildResourceStack}-ArtifactBucket"

  DogswatchWebhook:
    Type: 'AWS::CodePipeline::Webhook'
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GitHubSecretToken
      RegisterWithThirdParty: true
      Filters:
        - JsonPath: "$.ref"
          MatchEquals: refs/heads/{Branch}
        - JsonPath: "$.head_commit.modified[*]"
          MatchEquals: "extras/dogswatch/VERSION"
      TargetPipeline: !Ref DogswatchCtrPipeline
      TargetAction: SourceAction
      TargetPipelineVersion: !GetAtt DogswatchCtrPipeline.Version
