[package]
name = "refresh-timestamp-lambda"
version = "0.1.0"
authors = ["Erikson Tung <etung@amazon.com>"]
edition = "2018"
autobins = false
build = "build.rs"

[dependencies]
lambda_runtime = "0.2.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.44"
log = "0.4.8"
simple_logger = "1.3.0"
simple-error = "0.2.1"
rusoto_s3 = "0.42.0"
rusoto_ssm = "0.42.0"
rusoto_sts = "0.42.0"
rusoto_core = "0.42.0"
chrono = "0.4"
failure = "0.1.6"
reqwest = { version = "0.9.17", default-features = false, features = ["rustls-tls"] }
tough = { version = "0.3.0", features = ["http"] }
ring = "0.16.9"
olpc-cjson = "0.1.0"
tempfile = "3.1.0"
envy = "0.4"

[build-dependencies]
cargo-readme = "3.1"

[[bin]]
name = "bootstrap"
path = "src/main.rs"