AWSTemplateFormatVersion: "2010-09-09"
Description: 'Creates an IAM role that allows access to the TUF timestamp metadata signing key'
Parameters:
  LambdaAccountId:
    Description: 'The AWS account where the lambda that needs access to the signing key resides'
    Type: String
  SigningKeyName:
    Description: 'The parameter name of the signing key to grant access to'
    Type: String
    AllowedPattern: ^/.*$
    Default: '/bottlerocket/root-key'
  KMSKeyId:
    Description: 'The key id of the KMS key used to encrypt the signing key parameter into a secure string'
    Type: String
Resources:
  TimestampSignerAccessRole:
    Type: AWS::IAM::Role
    Properties:
      Description: 'Role allowing access to the signing key'
      Path: !Sub '/${AWS::StackName}/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub '${LambdaAccountId}'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'SigningKeyAccess'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: !Sub 'arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter${SigningKeyName}'
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: !Sub 'arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${KMSKeyId}'
Outputs:
  Role:
    Description: 'The ARN of the timestamp signing role'
    Value: !GetAtt TimestampSignerAccessRole.Arn
