version: 2
updates:

  - package-ecosystem: "cargo"
    directory: "/sources"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/tools"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/sources/host-ctr"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
