linters:
  enable:
    - errcheck
    - goimports
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused
    - vet

run:
  timeout: 3m
issues:
  exclude-dirs:
    - vendor
    - .gomodcache
