[package]
name = "kernel-5_15"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[package.metadata.build-package]
variant-sensitive = "platform"
package-name = "kernel-5.15"

[lib]
path = "../packages.rs"

[[package.metadata.build-package.external-files]]
# Use latest-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/42ac40513bf403555b444c8eb2792a334a4db9983e83106d6a75b335e0ab1a92/kernel-5.15.148-97.161.amzn2.src.rpm"
sha512 = "2c8f6886da223166196a969ef58f4abaf2549cbe3407599ce92e0529954f520f4eb4d7aaa0574eba38cf64e999b1de4e25c7f237a04b484bd810236a57e3679d"

[build-dependencies]
microcode = { path = "../microcode" }
