[package]
name = "kernel-5_15"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[package.metadata.build-package]
variant-sensitive = "platform"
package-name = "kernel-5.15"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
# Use latest-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/d1c204396a053805c433aec2591d8c5f2c853b62fe31ca3c04ad868a32659245/kernel-5.15.75-48.135.amzn2.src.rpm"
sha512 = "601ac4403f4109a823339fc17c62b21b47afe7d6853735aadd93236edd7d8c9ac88e3021eb1a78e82790f2aa3599bfcb349d0bb0389adb62167fc28b22e83ee8"

[build-dependencies]
microcode = { path = "../microcode" }
