[package]
name = "kernel-5_15"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[package.metadata.build-package]
package-name = "kernel-5.15"

[lib]
path = "../packages.rs"

[[package.metadata.build-package.external-files]]
# Use latest-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/1db73ff2ad4ac5d6ccf1f53e405b23ad5ee2715a6392faad73688bbb29c3374e/kernel-5.15.166-111.163.amzn2.src.rpm"
sha512 = "59de7f13b4ab203b17ed4c1fb8260db560f95ade10f31db7c609129cc3043781a76eca79ca293ff9addff88431b5c20072472e952d6d75749b93d282d4cab374"

[build-dependencies]
microcode = { path = "../microcode" }
