[package]
name = "kernel-5_15"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[package.metadata.build-package]
variant-sensitive = "platform"
package-name = "kernel-5.15"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
# Use latest-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/a05414b6b80f2113b47d97b12e0a706c05597c2dd2100da31341333605de9209/kernel-5.15.106-64.140.amzn2.src.rpm"
sha512 = "0a5a0319bd4c019a31d8139f4b5468ca0abc989f1846f4a7ae90c05e90be29119d33d43dc64cd39ddbcd0bf6b445aaa7379d0ca6392c146afa34c64f6dbb156f"

[build-dependencies]
microcode = { path = "../microcode" }
