[package]
name = "kernel-5_15"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[package.metadata.build-package]
variant-sensitive = "platform"
package-name = "kernel-5.15"

[lib]
path = "../packages.rs"

[[package.metadata.build-package.external-files]]
# Use latest-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/099e5401bd8b5ffe59330ca1179847c32a481136173f21b7af16d20b780de422/kernel-5.15.148-97.158.amzn2.src.rpm"
sha512 = "b2a1169b1d11ca4a93a4267d4d88fb97a87481a3b8f60702c0715fa2ad73d05a3b4ac74d25dd2cea2410038d58d8b6783a25382b3fb68879821595b1d42b230d"

[build-dependencies]
microcode = { path = "../microcode" }
