[package]
name = "kmod-6_1-nvidia"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "/dev/null"

[package.metadata.build-package]
package-name = "kmod-6.1-nvidia"
releases-url = "https://docs.nvidia.com/datacenter/tesla/"

[[package.metadata.build-package.external-files]]
url = "https://us.download.nvidia.com/tesla/525.105.17/NVIDIA-Linux-x86_64-525.105.17.run"
sha512 = "1a44a8d92d8434d356dcd6087c8a3277136e0819ffa5e4b6895854811cf63e44ad3dc08e0d248f149f8dc2280ab0993be6ee7fdf3c676fb9a85ff3dce83fd69a"

[[package.metadata.build-package.external-files]]
url = "https://us.download.nvidia.com/tesla/525.105.17/NVIDIA-Linux-aarch64-525.105.17.run"
sha512 = "75192acf8448a206a956b94b01b5e1e05cd21c7f172557bd6a2d1f1d92877583734c7e0998cedc3b54a8bdc5c7e869531ddea4161639daf40cbd0bf035252759"
[build-dependencies]
glibc = { path = "../glibc" }
kernel-6_1 = { path = "../kernel-6.1" }
