[package]
name = "update_sign_tuf_repo"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
data_store_version = { path = "../../workspaces/api/data_store_version" }
envy = "0.4.0"
hex = "0.4.0"
log = "0.4.8"
olpc-cjson = "0.1.0"
ring = { version = "0.16.7", features = ["std"] }
rusoto_core = "0.42.0"
rusoto_ssm = "0.42.0"
rusoto_sts = "0.42.0"
semver = { version = "0.9.0", features = ["serde"] }
serde = "1.0.101"
serde_json = "1.0.41"
serde_derive = "1.0.103"
simplelog = "0.7"
snafu = "0.6.0"
tempdir = "0.3.7"
tough = { version = "0.3.0", features = ["http"]  }
tracing = "0.1.10"
update_metadata = { path = "../../workspaces/updater/update_metadata" }

[build-dependencies]
cargo-readme = "3.1"
