# stack-name: host-containers-pr-build

Parameters:
  BuildSpecPath:
    Type: String
    AllowedPattern: '.+\.yml$'
    Default: "./tools/infra/buildspec/host-containers-pr-build.yml"
    Description: "The path to the buildspec.yml file to use."
  SourceGitHubRepositoryURL:
    Type: String
    Default: "https://github.com/amazonlinux/PRIVATE-thar.git"
    AllowedPattern: 'https://github.com/.+/.+\.git$'
    ConstraintDescription: "Source URL must be a GitHub repository (with its .git suffix)"
    Description: >-
      The GitHub repository that builds run for. Your account must be authorized
      to modify this repository's settings.
Resources:
  BuildLogBucket:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  BuildLogGroup:
    Type: AWS::Logs::LogGroup

  BuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com

  BuildRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref BuildRole
      PolicyName: BuildRolePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # For managing cache, logs, and artifacts in the build's buckets.
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource:
              - !GetAtt BuildLogBucket.Arn
              - Fn::Join:
                  - ""
                  - - !GetAtt BuildLogBucket.Arn
                    - /*
          # For writing to CloudWatch Logs Streams for each build.
          - Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - !GetAtt BuildLogGroup.Arn

  HostContainersPRBuild:
    Type: AWS::CodeBuild::Project
    DependsOn:
      - BuildLogGroup
      - BuildLogBucket
      - BuildRole
    Properties:
      LogsConfig:
        S3Logs:
          Status: ENABLED
          Location:
            Fn::Join:
              - "/"
              - - !GetAtt BuildLogBucket.Arn
                - "codebuild/log"
        CloudWatchLogs:
          Status: ENABLED
          GroupName: !Ref BuildLogGroup
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_LARGE
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      ServiceRole: !GetAtt BuildRole.Arn
      Source:
        BuildSpec: !Ref BuildSpecPath
        Location: !Ref SourceGitHubRepositoryURL
        ReportBuildStatus: true
        Type: GITHUB
      TimeoutInMinutes: 60
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED

Outputs:
  LogBucket:
    Value: !Ref BuildLogBucket
  Project:
    Value: !Ref HostContainersPRBuild
