Resources:
  BuildLogBucket:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  BuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: "2012-10-17"
  BuildRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - BuildLogBucket
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - BuildLogBucket
                        - Arn
                    - /*
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: BuildProject
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: BuildProject
                    - :*
        Version: "2012-10-17"
      PolicyName: BuildRolePolicy
      Roles:
        - Ref: BuildRole
  BuildProject:
    Type: AWS::CodeBuild::Project
    DependsOn:
      - BuildLogBucket
      - BuildRole
    Properties:
      LogsConfig:
        S3Logs:
          Status: ENABLED
          Location:
            Fn::Join:
              - "/"
              - - Fn::GetAtt:
                  - BuildLogBucket
                  - Arn
                - "codebuild/log"
        CloudWatchLogs:
          Status: ENABLED
      Environment:
        ComputeType: BUILD_GENERAL1_LARGE
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      ServiceRole:
        Fn::GetAtt:
          - BuildRole
          - Arn
      Source:
        BuildSpec: tools/infra/buildspec/host-containers-pr-build.yml
        Location: https://github.com/amazonlinux/PRIVATE-thar.git
        ReportBuildStatus: true
        Type: GITHUB
      TimeoutInMinutes: 60
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED

Outputs:
  LogBucket:
    Value:
      Ref: BuildLogBucket
  Project:
    Value:
      Ref: BuildProject
