gppParameters:
  BuildSpecPath:
    Type: String
    AllowedPattern: '.+\.yml$'
    Default: "./tools/infra/buildspec/infra-pr-build.yml"
    Description: "The path to the buildspec.yml file to use."
  SourceGitHubRepositoryURL:
    Type: String
    Default: "https://github.com/amazonlinux/PRIVATE-thar.git"
    AllowedPattern: 'https://github.com/.+/.+\.git$'
    ConstraintDescription: "Source URL must be a GitHub repository (with its .git suffix)"
    Description: >-
      The GitHub repository that builds run for. Your account must be authorized
      to modify this repository's settings.

Resources:
  BuildArtifactBucket:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  BuildLogBucket:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  BuildLogGroup:
    Type: AWS::Logs::LogGroup

  BuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com

  BuildRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - Ref: BuildRole
      PolicyName: BuildRolePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # For validation API usage performed on templates during build.
          - Action:
              - cloudformation:ValidateTemplate
            Effect: Allow
          # For managing cache, logs, and artifacts in the build's buckets.
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource:
              - !GetAtt BuildArtifactBucket.Arn
              - Fn::Join:
                  - ""
                  - - !GetAtt BuildArtifactBucket.Arn
                    - /*
              - !GetAtt BuildLogBucket.Arn
              - Fn::Join:
                  - ""
                  - - !GetAtt BuildLogBucket.Arn
                    - /*
          # For writing to CloudWatch Logs Streams for each build.
          - Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - !GetAtt BuildLogGroup.Arn

  InfraPRBuild:
    Type: AWS::CodeBuild::Project
    DependsOn:
      - BuildArtifactBucket
      - BuildLogBucket
      - BuildLogGroup
      - BuildRole
    Properties:
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        Type: LINUX_CONTAINER
      ServiceRole:
        Fn::GetAtt:
          - BuildRole
          - Arn
      Source:
        BuildSpec: !Ref BuildSpecPath
        Location: !Ref SourceGitHubRepositoryURL
        ReportBuildStatus: true
        Type: GITHUB
      LogsConfig:
        S3Logs:
          Status: ENABLED
          Location:
            Fn::Join:
              - "/"
              - - !GetAtt BuildArtifactBucket.Arn
                - "codebuild/log"
        CloudWatchLogs:
          Status: ENABLED
          GroupName: !Ref BuildLogGroup
      TimeoutInMinutes: 10
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED

Outputs:
  ArtifactBucket:
    Value:
      Ref: BuildArtifactBucket
  LogBucket:
    Value:
      Ref: BuildLogBucket
  Project:
    Value:
      Ref: InfraPRBuild
