# This is expected to be used by the account that owns the keys
# for TUF repo signing and should be stood up with those resources.
AWSTemplateFormatVersion: "2010-09-09"
Description: 'A role that allows read-only access to signing keys'
Parameters:
  AllowedAccountIds:
    Description: 'The AWS accounts that require access to the signing key'
    # A comma separated list of account ids, i.e "1234, 5678"
    Type: CommaDelimitedList
  KMSKeyArn:
    Description: "ARN of the KMS key required to decrypt the signing key in the SSM Parameter's SecureString"
    Type: String
  SigningKeyArn:
    Description: 'The ARN of the signing key SSM parameter'
    Type: String

Resources:
  SigningAutomationAccessRole:
    Type: AWS::IAM::Role
    Properties:
      Description: 'Role allowing access to the signing key'
      Path: !Sub '/${AWS::StackName}/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref AllowedAccountIds
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'SigningKeyReadOnlyAccess'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:Get*
                Resource: !Sub '${SigningKeyArn}'
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: !Sub '${KMSKeyArn}'
Outputs:
  Role:
    Description: 'The ARN of the signing key read-only role'
    Value: !GetAtt SigningAutomationAccessRole.Arn
