# This is expected to be used by the account that owns the CodeBuild projects
# for pipeline automation and should be stood up with those resources.
AWSTemplateFormatVersion: "2010-09-09"
Description: 'A policy that can be added to an existing role, allowing it to assume a role that allows access to signing keys'
Parameters:
  SigningRoleArn:
    Description: 'The ARN of the role that allows access to the signing keys'
    Type: String

Resources:
  AssumeSigningRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: 'Allows assume role access to read-only signing keys'
      ManagedPolicyName: SigningKeyAssumeRolePolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Resource: !Sub '${SigningRoleArn}'
