[package]
name = "microcode"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

# Check the two upstream repositories for the latest releases

[[package.metadata.build-package.external-files]]
url = "https://www.kernel.org/pub/linux/kernel/firmware/linux-firmware-20231111.tar.xz"
sha512 = "dd8eb7e8a51fe14479e2f4e1081a8a31f13d041ddd6180eaae6fe865dbad303c89aaaed2b9df237923f74f1cf9fe8c2e5492b4de5fce991ddb02bb091c95dc58"

[[package.metadata.build-package.external-files]]
url = "https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/archive/refs/tags/microcode-20231114.tar.gz"
sha512 = "a684444ef81e81687ff43b8255e95675eed1d728053bb1a483a60e94e2d2d43f10fc12522510b22daf90c4debd8f035e6b9a565813aa799c2e1e3a464124f59b"
