[package]
name = "kernel-5_10"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[package.metadata.build-package]
package-name = "kernel-5.10"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
# Use latest-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/67866b408c9bc8889fd8b86dab6fe79e697ac5ef31d321f173b028bf26dcf266/kernel-5.10.59-52.142.amzn2.src.rpm"
sha512 = "bbd90bd9793218f9410ca5d953a718fc00ed212953ea7de889698f66388314ecff4f145b2beb90ebff0bac6e961c6b3b71ca18948dc83194dd2e70feba7cf1db"
