[package]
name = "kernel-5_10"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[package.metadata.build-package]
variant-sensitive = "platform"
package-name = "kernel-5.10"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
# Use latest-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/c945e51a5ad81a6fd3ec405e57ad4ccd8ea44c8e26b1165771768e3da28fc382/kernel-5.10.176-157.645.amzn2.src.rpm"
sha512 = "57bb9eb168ad6051c7a8e938edb5f70ef9a1234a5e32f31a96dcb6dec8e3a48e3b4ba41f00fd5ea2934c89bb28c37c5553dc34e96345c354b563707ae52ae59d"

[build-dependencies]
microcode = { path = "../microcode" }
