[package]
name = "kernel-5_10"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[package.metadata.build-package]
package-name = "kernel-5.10"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
# Use latest-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/c80d649c51b68fdb2bc126c326f83fed93ed242d675f978a9a0da4012e9789a5/kernel-5.10.93-87.444.amzn2.src.rpm"
sha512 = "1e5442b0da15123e6a3c6c6b32f8f3b2ff53565fb9f2a76b778b315ea484a87423fef05bb1aed501c1a1f61507d5edac23bf1b1694bab3a73610ac6af22b190e"

[build-dependencies]
microcode = { path = "../microcode" }
