[package]
name = "kernel"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
# Use latest-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/8a2ede840234ebc72d835fab144162ba8184b8aa7df163a5d36aad2d3c85529b/kernel-5.4.16-8.72.amzn2.src.rpm"
sha512 = "0f9e04c94fe89b710bd9ad9bdb6ed075aaea30e4fd64c5ab9d42d2a052acd6abf6b91cd6aa561fd13559eed6cc27acb883e8cb27e113db34de29f6f905dd2bfc"
