[package]
name = "kernel"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
# Use latest-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/376c4a8ffedb59b2a17019fd74811a1f804ca1edcdfb71cab6f64222052631b0/kernel-4.19.72-25.58.amzn2.src.rpm"
sha512 = "ff1722d9b21a2c6f9f10600268a68929e1a600254aa25e7621df1006ea62750d892c2503fdc929a355f0a9d70c019202af744803892fade7e6bd8b2977fb3539"

[build-dependencies]
buildsys = { path = "../../tools/buildsys" }
sdk = { path = "../sdk", optional=true }

[features]
cascade = [ "sdk" ]
