[package]
name = "kernel-5_4"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[package.metadata.build-package]
package-name = "kernel-5.4"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
# Use latest-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/9e8b76ee271c50b0190e45d6b3fb69263afc7c8be8c1c3aafc4e663f997a0232/kernel-5.4.141-67.229.amzn2.src.rpm"
sha512 = "2f980b006579d3297481e0e8f8b636501648b05ae50e48a90ac1b576a47745dd9ab45fa92c7c094f7bff6931c502da2af1a3588f96e362a624d33767601d03b6"

# RPM BuildRequires
[build-dependencies]
# Provided by Bottlerocket SDK
