[package]
name = "kernel-5_4"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[package.metadata.build-package]
package-name = "kernel-5.4"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
# Use latest-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/30c599278ce31259b6ad8fcfb05d25c9bdbbdce8398f0ca686e70c36e7b4986b/kernel-5.4.110-54.189.amzn2.src.rpm"
sha512 = "ad38a02ec569dcd088e4013f2c9aa50ddf50775b4ded9da5ca367ae19cd141a7d7cd539c986cdcd70656a17e3e9fe874332942bdb027462ef0e029ac1c5fc38b"

# RPM BuildRequires
[build-dependencies]
# Provided by Bottlerocket SDK
