[package]
name = "kernel-5_4"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[package.metadata.build-package]
package-name = "kernel-5.4"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
# Use latest-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/1f5404c1e1cc923f488ae6290e17b38ac000e32e35364a0d7b567dda0ecba127/kernel-5.4.156-83.273.amzn2.src.rpm"
sha512 = "c41e5913ec7786a17498b1032e973c0f139eadbafec2834527c3efdcb3371a316015a209b6ab82e863f08d62c7161da7fbc117b79c8d936afea64253a77c3df8"

[build-dependencies]
microcode = { path = "../microcode" }
