version: 0.2

phases:
  pre_build:
    commands:
      - environment-report
      - write-build-meta
  build:
    commands:
      - sign-tuf-repo

artifacts:
  base-directory: '/tmp/tuf_out'
  files:
    - '*'
  secondary-artifacts:
    meta:
      base-directory: 'build/meta'
      files:
        - '*'
