version: 0.2

phases:
  pre_build:
    commands:
      - start-build-environment
      - environment-report
      - write-build-meta
  build:
    commands:
      - cargo make world

artifacts:
  base-directory: 'build/'
  files:
    - '*.img*'
    - '*.ext4*'
    - '*.verity*'
  secondary-artifacts:
    meta:
      base-directory: 'build/meta'
      files:
        - '*'
