version: 0.2

env:
  variables:
    # Path to infra tooling directory.
    INFRA_DIR: "./tools/infra"
    # Path to host containers folder
    EXTRAS_DIR: "./extras"
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - . "${INFRA_DIR}/env/lib/environment-setup"
  pre_build:
    commands:
      - environment-report
      - write-build-meta
  build:
    commands:
      - docker load -i ${CODEBUILD_SRC_DIR_BuildArtifact}/${CONTAINER_IMAGE}.tar.gz
      - $(aws ecr get-login --registry-ids ${ECR_ACCT_ID} --no-include-email --region us-west-2)
      - IMG_VER=$(grep "DOGSWATCH_VERSION=" ${EXTRAS_DIR}/dogswatch/Makefile | sed 's:.*=::')
      - docker tag "${CONTAINER_IMAGE}":latest "${ECR_ACCT_ID}".dkr.ecr.us-west-2.amazonaws.com/"${CONTAINER_IMAGE}":"${IMG_VER}_${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - docker push "${ECR_ACCT_ID}".dkr.ecr.us-west-2.amazonaws.com/"${CONTAINER_IMAGE}":"${IMG_VER}_${CODEBUILD_RESOLVED_SOURCE_VERSION}"
