version: 0.2

env:
  variables:
    # Path to infra tooling directory.
    INFRA_DIR: "./tools/infra"
    # Path to host containers folder
    EXTRAS_DIR: "./extras"
    # Path to built host container images
    IMAGES_DIR: "./build/host-container-images"
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - . "${INFRA_DIR}/env/lib/environment-setup"
  pre_build:
    commands:
      - write-build-meta
      - mkdir -p "${IMAGES_DIR}"
  build:
    commands:
      - make -C "${EXTRAS_DIR}/dogswatch" release-container
      - docker save dogswatch | gzip > "${IMAGES_DIR}"/dogswatch.tar.gz
artifacts:
  base-directory: '${IMAGES_DIR}'
  files:
    - '*.tar.gz'
  secondary-artifacts:
    meta:
      base-directory: 'build/meta'
      files:
        - '*'
