version: 0.2

env:
  variables:
    # Path to infra tooling directory.
    INFRA_DIR: "./tools/infra"

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - . "${INFRA_DIR}/env/lib/environment-setup"
      - . setup-rust-builder
      # TODO: rely on libsystemd in build container instead, see #545
      - apt install -y libsystemd-dev
  pre_build:
    commands:
      - environment-report
      - write-build-meta
  build:
    commands:
      # Run rust workspaces and go unit tests
      - cargo make unit-tests
