version: 0.2

env:
  variables:
    # Explicitly permit use of sources lookaside cache.
    BUILDSYS_ALLOW_UPSTREAM_SOURCE_URL: "true"
    # Path to infra tooling directory.
    INFRA_DIR: "./tools/infra"

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - . "${INFRA_DIR}/env/lib/environment-setup"
      - . install-rust-builder
  pre_build:
    commands:
      - environment-report
      - write-build-meta
      - start-buildkitd-daemon
  build:
    commands:
      # Retry fetches a few times before failing
      - retry 2 'fetch dependencies' -- cargo make fetch
      - cargo make world-packages
      - cargo make world-images
      - write-build-manifest

artifacts:
  base-directory: 'build/'
  files:
    - '*.img*'
    - '*.sha256'
  secondary-artifacts:
    meta:
      base-directory: 'build/meta'
      files:
        - '*'
