version: 0.2

phases:
  pre_build:
    commands:
      - start-build-environment
      - environment-report
      - write-build-meta
  build:
    commands:
      # Run rust workspaces and go unit tests
      - cargo make unit-tests
