[package]
name = "kmod-6_1-neuron"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
package-name = "kmod-6.1-neuron"
releases-url = "https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/runtime/aws-neuronx-dkms/index.html"

[[package.metadata.build-package.external-files]]
url = "https://yum.repos.neuron.amazonaws.com/aws-neuronx-dkms-2.17.17.0.noarch.rpm"
sha512 = "8ff07280fc2864677d9401d56939f8b8f8cd59dc1ae9df53d49aced500cd62c3071a61639e9f5381b557d29cc7a2b72be71020f90880680a59d10a1f8b28580b"

[build-dependencies]
kernel-6_1 = { path = "../kernel-6.1" }
