[package]
name = "kernel-6_1"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[package.metadata.build-package]
variant-sensitive = "platform"
package-name = "kernel-6.1"

[lib]
path = "../packages.rs"

[[package.metadata.build-package.external-files]]
# Use latest-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/al2023/blobstore/bb5b0dc5f0e4b3b6c9174c124b0ed7b8a4a9c500b4f2a9ef64a7ac6a44f6c2bc/kernel-6.1.77-99.164.amzn2023.src.rpm"
sha512 = "a504e14b35437ea3455a3a719e54c5da6520a49ab8026126d10e6ad3fbb079944b9be8d52cd966d750fd8cb77efe11fb76509c1c2fe9418e92dff81d227b5af4"

[build-dependencies]
microcode = { path = "../microcode" }
