name: Build
on:
  pull_request:
    branches: [develop]
    # Here we list file types that don't affect the build and don't need to use
    # up our Actions runners.
    paths-ignore: 
      # draw.io (diagrams.net) files, the source of png images for docs
      - '**.drawio'
      # Example configuration files
      - '**.example'
      # Markdown documentation
      - '**.md'
      # Images for documentation
      - '**.png'
      # Templates for README files
      - '**.tpl'
      # Sample config files and OpenAPI docs
      - '**.yaml'

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    continue-on-error: ${{ matrix.supported }}
    strategy:
      matrix:
        variant: [aws-k8s-1.18, aws-k8s-1.19, aws-k8s-1.20, aws-k8s-1.21, aws-ecs-1]
        arch: [x86_64, aarch64]
        supported: [true]
        include:
          - variant: aws-dev
            arch: x86_64
            supported: false
          - variant: vmware-dev
            arch: x86_64
            supported: false
          - variant: metal-dev
            arch: x86_64
            supported: false
          - variant: vmware-k8s-1.20
            arch: x86_64
            supported: true
          - variant: vmware-k8s-1.21
            arch: x86_64
            supported: true
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: rustup toolchain install 1.56.1 && rustup default 1.56.1
      - run: cargo install --version 0.30.0 cargo-make
      - run: cargo make -e BUILDSYS_VARIANT=${{ matrix.variant }} unit-tests
      - run: cargo make -e BUILDSYS_VARIANT=${{ matrix.variant }} check-fmt
      - run: cargo make -e BUILDSYS_VARIANT=${{ matrix.variant }} -e BUILDSYS_ARCH=${{ matrix.arch }} -e BUILDSYS_JOBS=12
