# This workflow caches crate dependencies and build artifacts for tools (except 'test-tools' since we don't use them in build workflows).
# The cache is only usable by workflows started from pull requests against the develop branch.
name: CacheDepsAndTools
on:
  push:
    branches: [develop]
    paths:
      - '.github/**'
      - 'sources/Cargo.lock'
      - 'tools/pubsys*/**'
      - '!tools/pubsys/policies/**'
      - '!tools/pubsys/**.example'
jobs:
  cache:
    if: github.repository == 'bottlerocket-os/bottlerocket'
    runs-on:
      group: bottlerocket
      labels: bottlerocket_ubuntu-latest_8-core
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Preflight step to set up the runner
        uses: ./.github/actions/setup-node
        with:
          perform-cache-cleanup: true
      - run: cargo make install-twoliter
      # This cleans the cargo cache in ~/.cargo
      - run: cargo-cache
